# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f119211b3aa8b3f0da34a366a351c50c1843de2398fa63e4f6466c4de389172d39c569ecae1ec098d5f070f3a3095f5216d0d8b587505c2458d33e7368544bed

test:
  secret_key_base: 8f9b9f58dbbbd20cf323ec3153167da38659284a257d985c11d5d84c03bf053c490b41683257d3e5386e793ef2d11d780d9efbbc016f6cdbd64c73743aa937ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
